"""add_work_orders_and_approvals

Revision ID: 355c26ac094f
Revises: 9a98d4f3ee8f
Create Date: 2026-06-27 21:01:41.619180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '355c26ac094f'
down_revision: Union[str, None] = '9a98d4f3ee8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('responsible_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_processes_project_id'), 'store_processes', ['project_id'], unique=False)
    op.create_index(op.f('ix_store_processes_status'), 'store_processes', ['status'], unique=False)
    op.create_index(op.f('ix_store_processes_tenant_id'), 'store_processes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_store_processes_work_type'), 'store_processes', ['work_type'], unique=False)
    op.create_table('store_service_forms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('contractor_company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_service_forms_month'), 'store_service_forms', ['month'], unique=False)
    op.create_index(op.f('ix_store_service_forms_project_id'), 'store_service_forms', ['project_id'], unique=False)
    op.create_index(op.f('ix_store_service_forms_status'), 'store_service_forms', ['status'], unique=False)
    op.create_index(op.f('ix_store_service_forms_tenant_id'), 'store_service_forms', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_store_service_forms_year'), 'store_service_forms', ['year'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_type', sa.Enum('MAINTENANCE', 'FAULT', 'REPAIR', 'RENOVATION', 'MANUFACTURING', 'OTHER', name='workordertype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assigned_to_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('assigned_to_phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('priority', sa.Enum('NORMAL', 'URGENT', 'CRITICAL', name='workorderpriority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'STARTED', 'COMPLETED', 'FAILED', 'CANCELLED', 'MATERIAL_WAITING', 'REVISIT', 'APPROVAL_PENDING', 'APPROVED', name='workorderstatus'), nullable=False),
    sa.Column('location_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_tenant_id'), 'work_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_orders_work_type'), 'work_orders', ['work_type'], unique=False)
    op.create_table('store_invoice_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('invoice_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['store_processes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_invoice_records_approval_status'), 'store_invoice_records', ['approval_status'], unique=False)
    op.create_index(op.f('ix_store_invoice_records_invoice_type'), 'store_invoice_records', ['invoice_type'], unique=False)
    op.create_index(op.f('ix_store_invoice_records_project_id'), 'store_invoice_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_store_invoice_records_tenant_id'), 'store_invoice_records', ['tenant_id'], unique=False)
    op.create_table('store_process_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('responsible_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['store_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_process_stages_order_index'), 'store_process_stages', ['order_index'], unique=False)
    op.create_index(op.f('ix_store_process_stages_process_id'), 'store_process_stages', ['process_id'], unique=False)
    op.create_table('store_progress_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('submitted_for_approval', sa.Boolean(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['store_processes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_progress_payments_approval_status'), 'store_progress_payments', ['approval_status'], unique=False)
    op.create_index(op.f('ix_store_progress_payments_payment_type'), 'store_progress_payments', ['payment_type'], unique=False)
    op.create_index(op.f('ix_store_progress_payments_process_id'), 'store_progress_payments', ['process_id'], unique=False)
    op.create_index(op.f('ix_store_progress_payments_project_id'), 'store_progress_payments', ['project_id'], unique=False)
    op.create_index(op.f('ix_store_progress_payments_tenant_id'), 'store_progress_payments', ['tenant_id'], unique=False)
    op.create_table('work_order_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_activities_activity_type'), 'work_order_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_work_order_activities_created_at'), 'work_order_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_order_activities_project_id'), 'work_order_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_order_activities_work_order_id'), 'work_order_activities', ['work_order_id'], unique=False)
    op.create_table('work_order_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('photo_type', sa.Enum('BEFORE', 'AFTER', 'COMPLETION', 'ISSUE', name='workorderphototype'), nullable=False),
    sa.Column('uploaded_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_photos_photo_type'), 'work_order_photos', ['photo_type'], unique=False)
    op.create_index(op.f('ix_work_order_photos_work_order_id'), 'work_order_photos', ['work_order_id'], unique=False)
    op.create_table('work_order_public_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_public_links_token'), 'work_order_public_links', ['token'], unique=True)
    op.create_index(op.f('ix_work_order_public_links_work_order_id'), 'work_order_public_links', ['work_order_id'], unique=False)
    op.create_table('work_order_service_forms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_service_forms_month'), 'work_order_service_forms', ['month'], unique=False)
    op.create_index(op.f('ix_work_order_service_forms_project_id'), 'work_order_service_forms', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_order_service_forms_work_order_id'), 'work_order_service_forms', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_work_order_service_forms_year'), 'work_order_service_forms', ['year'], unique=False)
    op.create_table('work_order_whatsapp_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('to_phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('whatsapp_message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='workorderwhatsappstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_whatsapp_messages_status'), 'work_order_whatsapp_messages', ['status'], unique=False)
    op.create_index(op.f('ix_work_order_whatsapp_messages_whatsapp_message_id'), 'work_order_whatsapp_messages', ['whatsapp_message_id'], unique=False)
    op.create_index(op.f('ix_work_order_whatsapp_messages_work_order_id'), 'work_order_whatsapp_messages', ['work_order_id'], unique=False)
    op.create_table('store_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_process_id', sa.Uuid(), nullable=True),
    sa.Column('related_stage_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['related_process_id'], ['store_processes.id'], ),
    sa.ForeignKeyConstraint(['related_stage_id'], ['store_process_stages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_activities_activity_type'), 'store_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_store_activities_created_at'), 'store_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_store_activities_project_id'), 'store_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_store_activities_tenant_id'), 'store_activities', ['tenant_id'], unique=False)
    op.create_table('store_approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('approval_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('related_payment_id', sa.Uuid(), nullable=True),
    sa.Column('related_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('requested_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['store_processes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['store_invoice_records.id'], ),
    sa.ForeignKeyConstraint(['related_payment_id'], ['store_progress_payments.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_approval_requests_approval_type'), 'store_approval_requests', ['approval_type'], unique=False)
    op.create_index(op.f('ix_store_approval_requests_project_id'), 'store_approval_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_store_approval_requests_status'), 'store_approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_store_approval_requests_tenant_id'), 'store_approval_requests', ['tenant_id'], unique=False)
    op.create_table('store_process_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('note_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['store_processes.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['store_process_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_process_notes_process_id'), 'store_process_notes', ['process_id'], unique=False)
    op.create_unique_constraint(None, 'role_permissions', ['role_id', 'permission_id'])
    op.create_unique_constraint('uq_stock_wh_mat', 'stock', ['warehouse_id', 'material_id'])
    op.create_unique_constraint(None, 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint('uq_stock_wh_mat', 'stock', type_='unique')
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_store_process_notes_process_id'), table_name='store_process_notes')
    op.drop_table('store_process_notes')
    op.drop_index(op.f('ix_store_approval_requests_tenant_id'), table_name='store_approval_requests')
    op.drop_index(op.f('ix_store_approval_requests_status'), table_name='store_approval_requests')
    op.drop_index(op.f('ix_store_approval_requests_project_id'), table_name='store_approval_requests')
    op.drop_index(op.f('ix_store_approval_requests_approval_type'), table_name='store_approval_requests')
    op.drop_table('store_approval_requests')
    op.drop_index(op.f('ix_store_activities_tenant_id'), table_name='store_activities')
    op.drop_index(op.f('ix_store_activities_project_id'), table_name='store_activities')
    op.drop_index(op.f('ix_store_activities_created_at'), table_name='store_activities')
    op.drop_index(op.f('ix_store_activities_activity_type'), table_name='store_activities')
    op.drop_table('store_activities')
    op.drop_index(op.f('ix_work_order_whatsapp_messages_work_order_id'), table_name='work_order_whatsapp_messages')
    op.drop_index(op.f('ix_work_order_whatsapp_messages_whatsapp_message_id'), table_name='work_order_whatsapp_messages')
    op.drop_index(op.f('ix_work_order_whatsapp_messages_status'), table_name='work_order_whatsapp_messages')
    op.drop_table('work_order_whatsapp_messages')
    op.drop_index(op.f('ix_work_order_service_forms_year'), table_name='work_order_service_forms')
    op.drop_index(op.f('ix_work_order_service_forms_work_order_id'), table_name='work_order_service_forms')
    op.drop_index(op.f('ix_work_order_service_forms_project_id'), table_name='work_order_service_forms')
    op.drop_index(op.f('ix_work_order_service_forms_month'), table_name='work_order_service_forms')
    op.drop_table('work_order_service_forms')
    op.drop_index(op.f('ix_work_order_public_links_work_order_id'), table_name='work_order_public_links')
    op.drop_index(op.f('ix_work_order_public_links_token'), table_name='work_order_public_links')
    op.drop_table('work_order_public_links')
    op.drop_index(op.f('ix_work_order_photos_work_order_id'), table_name='work_order_photos')
    op.drop_index(op.f('ix_work_order_photos_photo_type'), table_name='work_order_photos')
    op.drop_table('work_order_photos')
    op.drop_index(op.f('ix_work_order_activities_work_order_id'), table_name='work_order_activities')
    op.drop_index(op.f('ix_work_order_activities_project_id'), table_name='work_order_activities')
    op.drop_index(op.f('ix_work_order_activities_created_at'), table_name='work_order_activities')
    op.drop_index(op.f('ix_work_order_activities_activity_type'), table_name='work_order_activities')
    op.drop_table('work_order_activities')
    op.drop_index(op.f('ix_store_progress_payments_tenant_id'), table_name='store_progress_payments')
    op.drop_index(op.f('ix_store_progress_payments_project_id'), table_name='store_progress_payments')
    op.drop_index(op.f('ix_store_progress_payments_process_id'), table_name='store_progress_payments')
    op.drop_index(op.f('ix_store_progress_payments_payment_type'), table_name='store_progress_payments')
    op.drop_index(op.f('ix_store_progress_payments_approval_status'), table_name='store_progress_payments')
    op.drop_table('store_progress_payments')
    op.drop_index(op.f('ix_store_process_stages_process_id'), table_name='store_process_stages')
    op.drop_index(op.f('ix_store_process_stages_order_index'), table_name='store_process_stages')
    op.drop_table('store_process_stages')
    op.drop_index(op.f('ix_store_invoice_records_tenant_id'), table_name='store_invoice_records')
    op.drop_index(op.f('ix_store_invoice_records_project_id'), table_name='store_invoice_records')
    op.drop_index(op.f('ix_store_invoice_records_invoice_type'), table_name='store_invoice_records')
    op.drop_index(op.f('ix_store_invoice_records_approval_status'), table_name='store_invoice_records')
    op.drop_table('store_invoice_records')
    op.drop_index(op.f('ix_work_orders_work_type'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_tenant_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_project_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_store_service_forms_year'), table_name='store_service_forms')
    op.drop_index(op.f('ix_store_service_forms_tenant_id'), table_name='store_service_forms')
    op.drop_index(op.f('ix_store_service_forms_status'), table_name='store_service_forms')
    op.drop_index(op.f('ix_store_service_forms_project_id'), table_name='store_service_forms')
    op.drop_index(op.f('ix_store_service_forms_month'), table_name='store_service_forms')
    op.drop_table('store_service_forms')
    op.drop_index(op.f('ix_store_processes_work_type'), table_name='store_processes')
    op.drop_index(op.f('ix_store_processes_tenant_id'), table_name='store_processes')
    op.drop_index(op.f('ix_store_processes_status'), table_name='store_processes')
    op.drop_index(op.f('ix_store_processes_project_id'), table_name='store_processes')
    op.drop_table('store_processes')
    # ### end Alembic commands ###
