"""add_work_order_soft_delete

Revision ID: 4b7e8d9c0a1b
Revises: 355c26ac094f
Create Date: 2026-06-28 19:02:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b7e8d9c0a1b'
down_revision: Union[str, None] = '355c26ac094f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('work_orders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('work_orders', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_work_orders_deleted_by_id_users', 'work_orders', 'users', ['deleted_by_id'], ['id'])
    op.create_index(op.f('ix_work_orders_is_deleted'), 'work_orders', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_is_deleted'), table_name='work_orders')
    op.drop_constraint('fk_work_orders_deleted_by_id_users', 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'deleted_by_id')
    op.drop_column('work_orders', 'deleted_at')
    op.drop_column('work_orders', 'is_deleted')
    # ### end Alembic commands ###
