"""sprint21_workflow_email_alerts

Revision ID: 660af244a23a
Revises: 024068998aaf
Create Date: 2026-07-07 12:41:46.094705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '660af244a23a'
down_revision: Union[str, None] = '024068998aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_tenant_settings', sa.Column('workflow_email_alerts_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('platform_tenant_settings', sa.Column('workflow_alert_recipients', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_tenant_settings', 'workflow_alert_recipients')
    op.drop_column('platform_tenant_settings', 'workflow_email_alerts_enabled')
    # ### end Alembic commands ###
