"""add_whatsapp_template_config

Revision ID: 7a8b9c0d1e2f
Revises: 4b7e8d9c0a1b
Create Date: 2026-06-28 19:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a8b9c0d1e2f'
down_revision: Union[str, None] = '4b7e8d9c0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop table if exists to bypass SQLModel auto-create conflicts
    op.execute("DROP TABLE IF EXISTS notification_template_configs CASCADE")

    op.create_table(
        'notification_template_configs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=True),
        sa.Column('event_key', sa.String(length=100), nullable=False),
        sa.Column('channel', sa.String(length=50), nullable=False),
        sa.Column('template_name', sa.String(length=120), nullable=False),
        sa.Column('language_code', sa.String(length=10), nullable=False, server_default='tr'),
        sa.Column('component_mapping_json', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_notification_template_configs_tenant_id_tenants'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_template_configs_channel'), 'notification_template_configs', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_template_configs_event_key'), 'notification_template_configs', ['event_key'], unique=False)
    op.create_index(op.f('ix_notification_template_configs_is_active'), 'notification_template_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_notification_template_configs_tenant_id'), 'notification_template_configs', ['tenant_id'], unique=False)

    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    columns = [c['name'] for c in inspector.get_columns('work_order_whatsapp_messages')]
    if 'whatsapp_audit_id' not in columns:
        op.add_column('work_order_whatsapp_messages', sa.Column('whatsapp_audit_id', sa.Uuid(), nullable=True))
        op.create_foreign_key('fk_wo_wa_msg_audit_id', 'work_order_whatsapp_messages', 'outbound_whatsapp_audits', ['whatsapp_audit_id'], ['id'])
    if 'created_at' not in columns:
        op.add_column('work_order_whatsapp_messages', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_wo_wa_msg_audit_id', 'work_order_whatsapp_messages', type_='foreignkey')
    op.drop_column('work_order_whatsapp_messages', 'created_at')
    op.drop_column('work_order_whatsapp_messages', 'whatsapp_audit_id')

    op.drop_index(op.f('ix_notification_template_configs_tenant_id'), table_name='notification_template_configs')
    op.drop_index(op.f('ix_notification_template_configs_is_active'), table_name='notification_template_configs')
    op.drop_index(op.f('ix_notification_template_configs_event_key'), table_name='notification_template_configs')
    op.drop_index(op.f('ix_notification_template_configs_channel'), table_name='notification_template_configs')
    op.drop_table('notification_template_configs')
    # ### end Alembic commands ###
