"""add_whatsapp_audit_columns

Revision ID: 9a98d4f3ee8f
Revises: 2b69ba90e234
Create Date: 2026-06-27 18:54:52.740323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a98d4f3ee8f'
down_revision: Union[str, None] = '2b69ba90e234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_whatsapp_audits', sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('outbound_whatsapp_audits', sa.Column('pricing_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_outbound_whatsapp_audits_conversation_id'), 'outbound_whatsapp_audits', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_whatsapp_audits_conversation_id'), table_name='outbound_whatsapp_audits')
    op.drop_column('outbound_whatsapp_audits', 'pricing_category')
    op.drop_column('outbound_whatsapp_audits', 'conversation_id')
    # ### end Alembic commands ###
