"""sprint19_workflow_engine

Revision ID: fb1e7542ac9e
Revises: b4f3c2d1e8a9
Create Date: 2026-07-06 18:04:29.978282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb1e7542ac9e'
down_revision: Union[str, None] = 'b4f3c2d1e8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label_tr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('required_feature', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('celery_task', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('endpoint_pattern', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_actions_action_type'), 'workflow_actions', ['action_type'], unique=True)
    op.create_table('workflow_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dsl_json', sa.Text(), nullable=False),
    sa.Column('required_modules', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required_features', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_is_published'), 'workflow_templates', ['is_published'], unique=False)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label_tr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('payload_schema', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_event_name'), 'workflow_triggers', ['event_name'], unique=True)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('trigger_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_tenant_id'), 'workflow_definitions', ['tenant_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('dsl_json', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_definition_id'), 'workflow_versions', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_version_number'), 'workflow_versions', ['version_number'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('trigger_event_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trigger_payload', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'trigger_event_ref', name='uq_workflow_run_event')
    )
    op.create_index(op.f('ix_workflow_runs_definition_id'), 'workflow_runs', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_version_id'), 'workflow_runs', ['version_id'], unique=False)
    op.create_table('workflow_run_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_nodes_run_id'), 'workflow_run_nodes', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_nodes_status'), 'workflow_run_nodes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_run_nodes_status'), table_name='workflow_run_nodes')
    op.drop_index(op.f('ix_workflow_run_nodes_run_id'), table_name='workflow_run_nodes')
    op.drop_table('workflow_run_nodes')
    op.drop_index(op.f('ix_workflow_runs_version_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_definition_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_versions_version_number'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_definition_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_definitions_tenant_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_workflow_triggers_event_name'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_workflow_templates_is_published'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_workflow_actions_action_type'), table_name='workflow_actions')
    op.drop_table('workflow_actions')
    # ### end Alembic commands ###
